### ISSUE TITLE
[TRACKER] Potential Development Halting Issues.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2220]
I have compiled a list of issues which might have a big impact on, or halt the development of a game. These are either issues that look bad or issues that several people have complained about and ran into issues completing a game with. This was made in light of mafiesto's intention to have at least a few commercial games on steam/other platforms, and consoles made with the engine.

Prefab issues:
- [ ] [Editing root of a model prefab not updating nested instances of it](https://github.com/FlaxEngine/FlaxEngine/issues/2085)
- [ ] [Various prefab bugs, maybe not relevant anymore](https://github.com/FlaxEngine/FlaxEngine/issues/1924)

Model importing issues:
  - [ ] [Some messy geometry on importing](https://github.com/FlaxEngine/FlaxEngine/issues/1660)
  - [ ] [General model importing concerns](https://github.com/FlaxEngine/FlaxEngine)
  
Lack of non-destructive workflow:
  - [ ] [Models/Model prefabs should keep track of existing sub-assets.](https://github.com/FlaxEngine/FlaxEngine/issues/2110)
  - [ ] [Inheritance of import settings](https://github.com/FlaxEngine/FlaxEngine/issues/2114)
  - [ ] [Generally related issue](https://github.com/FlaxEngine/FlaxEngine/issues/426)

Animation Issues:
- [ ] [Animation inconsistencies](https://github.com/FlaxEngine/FlaxEngine/issues/2152)
- [ ] [Animation retargetting issue](https://github.com/FlaxEngine/FlaxEngine/issues/1517)
- [ ] [Root motion issue (but some others had working root motion)](https://github.com/FlaxEngine/FlaxEngine/issues/1429)

- [ ] [3D audio broken in large worlds](https://github.com/FlaxEngine/FlaxEngine/issues/2015)
- [ ] [Physical materials are lacking (i reported as well)](https://github.com/FlaxEngine/FlaxEngine/issues/1112)
- [ ] [OpenAL quality issue](https://github.com/FlaxEngine/FlaxEngine/issues/1032)
- [ ] [XAudio2 issue](https://github.com/FlaxEngine/FlaxEngine/issues/1612)
- [ ] [#networking on discord](https://discord.com/channels/437989205315158016/790657182088691805) has lots of issues
- [ ] [Icon does not export](https://github.com/FlaxEngine/FlaxEngine/issues/928)
- [ ] Game exe name doesn't export
- [ ] [DDGI and SDF issue](https://github.com/FlaxEngine/FlaxEngine/issues/1614)
- [ ] Shadow rendering is more expensive than it should be according to mafi, and should be cached or smth. I noticed this when trying to shadow a large area without having blinding obvious shadows missing close to the camera.
- [ ] Mouse inputs are sometimes unreliable according to several reports
- [ ] [Several Complaints about using the terrain system](https://forum.flaxengine.com/t/terrain-issues-with-details-1-7-6/1562)
- [ ] [Terrain painting problems (someone is working on it I think)](https://github.com/FlaxEngine/FlaxEngine/issues/1654)
- [ ] [Broken transforms on model prefab reimport (excluded from last list as I made a fix for this one)](https://github.com/FlaxEngine/FlaxEngine/issues/2113)
- [ ] [Raycast issue with character controllers](https://github.com/FlaxEngine/FlaxEngine/issues/1935)
- [ ] [These are all important networking issues, but already in the 1.8 milestone.](https://github.com/FlaxEngine/FlaxEngine/issues?q=is%3Aopen+label%3Anetworking+milestone%3A1.8)
- [ ] Lightmap baking does not work, increasing the importance that DDGI work nicely.

**Comment by abrasivetroop** [comment]
Thank you again for putting this together. This outlines most of the major development halting problems with Flax. Hoping that these issues will be addressed asap.

**Comment by Tryibion** [comment]
Wasn't the game exe name changing added in 1.8 already?

**Comment by Menotdan** [comment]
> Wasn't the game exe name changing added in 1.8 already? (I haven't tested it, but thought I saw it go through)

Yes, but its not been released to anything accessible through the launcher so I chose to leave it in for now.

**Comment by Muzz** [comment]
https://github.com/FlaxEngine/FlaxEngine/issues/2413

This issue atm is the biggest source of jank and a feeling of brokenness to our character controller atm. 

We are making quite a large game with a team of 7 devs, so If it helps prioritize we can put our thoughts in here?

**Comment by Menotdan** [comment]
> #2413
> 
> This issue atm is the biggest source of jank and a feeling of brokenness to our character controller atm.
> 
> We are making quite a large game with a team of 7 devs, so If it helps prioritize we can put our thoughts in here?

Sure, you can add whatever you like here and I can add it to the list if its important

**Comment by Menotdan** [comment]
I am removing all completed tasks to clear things up a bit. If you want to look at the old list, check the revisions of the comment.
